name: msn
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.4.1 <4.0.0"

dependencies:
    firebase_core: ^2.32.0
    firebase_auth: ^4.20.0
    flutter:
        sdk: flutter
    google_sign_in: ^6.2.1
    supabase_flutter: ^2.5.4
    flutter_dotenv: ^5.1.0
    timeago: ^3.6.1
    powersync: ^1.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0
    vibration: ^1.9.0

flutter:
    uses-material-design: true
    assets:
        - .env
